name: Cronjob

on:
  push:
    branches: [ 2020/jan/gha1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make dummy artifact file
      run: |
        mkdir -p output/test
        date >   output/test/output1.txt

    - name: Install composer.json packages
      run: |
        composer self-update
        composer update --no-interaction

    - name: Log file
      uses: actions/upload-artifact@v2
      with:
        name: Log-file-report
        path: output/test/output1.txt
        

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
