name: Cronjob
env:
  DB: mysql
  
on:
  push:
    branches: [ 2020/jan/gha1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP with selected extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'

    - name: Make dummy artifact file
      run: |
        mkdir -p output/test
        date >   output/test/output1.txt

    - name: debug setup machine for FileSender
      run: ls -l 

    - name: setup machine for FileSender
      run: ci/setup-machine.sh


    - name: Log file
      uses: actions/upload-artifact@v2
      with:
        name: Log-file-report
        path: output/test/output1.txt
        

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
