name: Cronjob
  
on:
  push:
    branches: [ 2020/jan/gha1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI-${{ matrix.testsuite }}-${{ matrix.db }}
    runs-on: Ubuntu-20.04

    strategy:
      matrix:
       include:
         - testsuite: "core"
           db: "mysql"
           travis_sauce_connect: false
           sauce_username: ""

    env:
      DB: ${{ matrix.db }}
      TESTSUITE: ${{ matrix.testsuite }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: filesender
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Checkout code from github
      uses: actions/checkout@v2


    - name: Make dummy artifact file
      run: |
        mkdir -p output/test
        date >   output/test/output1.txt
        BASEDIR=$(pwd)
        export BASEDIR



    - name: setup machine for FileSender
      run: ci/setup-machine.sh
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432




    - name: Log file
      uses: actions/upload-artifact@v2
      with:
        name: Log-file-report
        path: output/test/output1.txt

    - name: FileSender Log files
      uses: actions/upload-artifact@v2
      with:
        name: Log-files
        path: log

    - name: log files open to read
      run: sudo chmod +r /var/log/apache2/error.log /var/log/apache2/access.log

    - name: Apache Log files
      uses: actions/upload-artifact@v2
      with:
        name: apache-logs
        path: |
          /var/log/apache2/error.log
          /var/log/apache2/access.log


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
